name: CI Check
on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python env check
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python --version